name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  merge-me:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
